spring.application.name=Axiom
spring.datasource.url=jdbc:postgresql://localhost:5432/axiomdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sameerog
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
